### PR TITLE
Update MGHPCC outage announcement

### PR DESCRIPTION
**Pull request by larsks**
Change severity from 2 -> 0 (will change back to `2` closer to the outage)

### CODE REVIEW

**Comment by larsks** [comment]
It looks like some some changes were pushed directly to the main branch. Please make sure to submit changes as pull requests.

**Comment by larsks** [comment]
~~@joachimweyl you removed the `active` tag here, but I'm pretty sure you want to keep that: we want this announcement to show up ahead of time, and inactive posts won't show up anywhere but in the archive. Was that intentional?~~

Never mind, I see you put it back :)

**Comment by joachimweyl** [comment]
This was my first Status update. I have a much better understanding of the proper steps and variables. This will not happen again.

**Review by joachimweyl — APPROVED** [review]
Thank you for repairing my learning mistakes.

**Pull request merged**
