### PR TITLE
Change outgoing support email

### PR DESCRIPTION
**Pull request by joachimweyl**
email changed to resolve "unauthenticated email from massopen.cloud is not accepted due to domain's
dmarc policy."

### CODE REVIEW

**Comment by naved001** [comment]
there's no content in the file.

**Comment by joachimweyl** [comment]
@naved001 I must have somehow not saved it after I pasted the text. Thank you for catching that. Fixed.

**Review by naved001 — APPROVED** [review]
looks good. I also tested opening a ticket by sending an email to the new address and that works as expected.

**Comment by naved001** [comment]
also added the new emails to approved senders to our ositcket lists email.

**Review by msdisme — COMMENTED** [review]
looks good!

**Pull request merged**
